version: "3.3"
services:

    csvserver:
        image: infracloudio/csvserver
        container_name: "csvserver"
        volumes:
          - ${PWD}/inputdata:/csvserver/inputdata
        ports:
          - 9393:9300
        environment:
            - CSVSERVER_BORDER=Orange

    prometheus:
        image: prom/prometheus:v2.22.0
        container_name: "prometheus"
        ports:
        - 9090:9090
        volumes:
        - ${PWD}/prometheus:/etc/prometheus
        command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
        depends_on:
        - csvserver
