version: "3"
services:

    csvserver:
        image: infracloudio/csvserver
        container_name: "csvserver"
        volumes:
          - ${PWD}/inputdata:/csvserver/inputdata
        ports:
          - 9393:9300
        environment:
            - CSVSERVER_BORDER=Orange
