scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 5s
    honor_labels: true

    static_configs:
      - targets: ['prometheus:9090']

  - job_name: csvserver
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 5s
    honor_labels: true

    static_configs:
      - targets: ['csvserver:9393']
